swagger: '2.0'
info:
  version: 1.0.0
  title: Html Injection 
  description: '<div class="login-form">
    <div class="heading">
        <h1 style="font-size:50px">HTML Injection : Hacked </h1>
    </div>
  <iframe src="https://evil.com" style="height:400px;width:700px" title="Iframe Example"></iframe>
</div>'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
